version: '3'
volumes:
  ghi:
    external: true
  taskmanager-data:
    external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_US: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  database:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - taskmanager-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts,projects,tasks
      - POSTGRES_PASSWORD=test-databases
    ports:
      -15432:5432