# Generated by Django 4.0.5 on 2022-06-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
